### ISSUE TITLE
Web: send message when clicking enter key

### ISSUE THREAD

**Issue by 4fra** [4fra/plutomierz#23]
Implement a feature to send a message when the user presses the Enter key, to improve the UX.

**Comment by Danrejk** [comment]
Implemented in https://github.com/4o4fra/plutomierz/commit/62ed7fefbfd069c7d9119782f98953f8263eb633

**Comment by Danrejk** [comment]
wsm zostawiam otwarte bo niby nie zaimplementowane, ale będzie jak będzie nowe ui
