### ISSUE TITLE
API: Pluta log crashes if client provides invalid date

### ISSUE THREAD

**Issue by 4fra** [4fra/plutomierz#31]
Expected Behavior:

- The API should handle invalid date formats gracefully and return an appropriate error message instead of crashing.

Actual Behavior:

- The API crashes when an invalid date format is provided.

Suggested Fix:
-  Add validation to check if the `fromDate` parameter is a valid date before using it in the query.

**Comment by 4fra** [comment]
@Danrejk explain what's wrong with the current error handling in pluta log

**Comment by Danrejk** [comment]
never mind it's all fine
